=== Djang0/limba/config/server.dtd
<!ELEMENT server    (db,usr,pws,publicCatId,rootCatId,contactCatId,HomepageId,HomepageCatId,encoding,controler,siteurl,sitename,sitetitle,info,noreply,layout+)>
<!ELEMENT db          (#PCDATA)>
<!ELEMENT usr          (#PCDATA)>
<!ELEMENT pws         (#PCDATA)>
<!ELEMENT publicCatId          (#PCDATA)>
<!ELEMENT rootCatId          (#PCDATA)>
<!ELEMENT contactCatId          (#PCDATA)>
<!ELEMENT HomepageId          (#PCDATA)>
<!ELEMENT HomepageCatId          (#PCDATA)>
<!ELEMENT encoding    (#PCDATA)>
<!ELEMENT controler   (#PCDATA)>
<!ELEMENT siteurl   (#PCDATA)>
<!ELEMENT sitename   (#PCDATA)>
<!ELEMENT sitetitle   (#PCDATA)>
<!ELEMENT info   (#PCDATA)>
<!ELEMENT noreply   (#PCDATA)>
<!ELEMENT layout    (logourl,basetemplate,maxRecurse,generators)>
<!ATTLIST layout name (index|admin|embed|xml|pdf) "index">
<!ELEMENT logourl   (#PCDATA)>
<!ELEMENT basetemplate   (#PCDATA)>
<!ELEMENT maxRecurse   (#PCDATA)>
<!ELEMENT generators    (ClassGenerator | FileContentGenerator)*>
<!ELEMENT ClassGenerator   (classname,substitutiontag)>
<!ELEMENT classname   (#PCDATA)>
<!ELEMENT substitutiontag   (#PCDATA)>
<!ELEMENT FileContentGenerator   (file,substitutiontag)>
<!ELEMENT file   (#PCDATA)>

=== Djang0/limba/dev-scripts/pack/packdirs/etc/limba/siteconf/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server SYSTEM "server.dtd">
<server>
        <db>mysql:host=localhost;dbname=limba;charset=utf8</db>
        <usr>{{{usr}}}</usr>
        <pws>{{{pws}}}</pws>
        <publicCatId>12</publicCatId>
        <rootCatId>1</rootCatId>
        <contactCatId>3</contactCatId>
        <HomepageId>1</HomepageId>
        <HomepageCatId>12</HomepageCatId>
        <encoding>UTF-8</encoding>
        <controler>/index.php</controler>
        <siteurl>http://data</siteurl>
        <sitename>limba</sitename>
        <sitetitle>Limba</sitetitle>
        <info>ludovic.reenaers@gmail.com</info>
        <noreply>ludovic.reenaers@gmail.com</noreply>
        <layout name="embed">
                <logourl>/img/user/wdge.png</logourl>
                <basetemplate>html/templates/EMBED</basetemplate>
                <maxRecurse>0</maxRecurse>
                <generators>
                      
                </generators>
        </layout>
        <layout name="xml">
                <logourl>/img/user/wdge.png</logourl>
                <basetemplate>html/templates/EMBED</basetemplate>
                <maxRecurse>0</maxRecurse>
                <generators>
                      
                </generators>
        </layout>
        <layout name="admin">
                <logourl>/img/user/logo.png</logourl>
                <basetemplate>html/templates/ADMIN</basetemplate>
                <maxRecurse>0</maxRecurse>
                <generators>
                                <FileContentGenerator>
                                        <file>html/encodings/XHTML1.0T</file>
                                        <substitutiontag>DOCTYPE</substitutiontag>
                                </FileContentGenerator>
                                <FileContentGenerator>
                                        <file>html/headers/BASE</file>
                                        <substitutiontag>METAHEAD</substitutiontag>
                                </FileContentGenerator>
                                <ClassGenerator>
										<classname>OldAdminMenuTreeGenerator</classname>
                                        <substitutiontag>MENUG</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>UserPadGenerator</classname>
                                        <substitutiontag>USERPAD</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>NotifyGenerator</classname>
                                        <substitutiontag>NOTIFY</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>AdminBreadCrumbGenerator</classname>
                                        <substitutiontag>PATHWAY</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>HtmlHeadAdminScriptsGenerator</classname>
                                        <substitutiontag>SCRIPTS</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>AdminBannerGenerator</classname>
                                        <substitutiontag>ADMHEADER</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>TitleGenerator</classname>
                                        <substitutiontag>TITLE</substitutiontag>
                                </ClassGenerator>
                </generators>
        </layout>
        <layout name="index">
                <logourl>/img/user/wdge.png</logourl>
                <basetemplate>html/templates/ERGONOMIC</basetemplate>
                <maxRecurse>0</maxRecurse>
                        <generators>
                                <FileContentGenerator>
                                        <file>html/encodings/XHTML1.0T</file>
                                        <substitutiontag>DOCTYPE</substitutiontag>
                                </FileContentGenerator>
                                <FileContentGenerator>
                                        <file>html/headers/BASE</file>
                                        <substitutiontag>METAHEAD</substitutiontag>
                                </FileContentGenerator>
                                <ClassGenerator>
                                        <classname>BreadCrumbGenerator</classname>
                                        <substitutiontag>BREADCRUMB</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>DynamicMenuTreeGenerator</classname>
                                        <substitutiontag>LEFTMENU</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>HeaderGenerator</classname>
                                        <substitutiontag>HEADER</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>NotifyGenerator</classname>
                                        <substitutiontag>NOTIFY</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>BreadCrumbGenerator</classname>
                                        <substitutiontag>PATHWAY</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>LanguagePadGenerator</classname>
                                        <substitutiontag>LANGUAGES</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>HtmlHeadScriptsGenerator</classname>
                                        <substitutiontag>SCRIPTS</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>TitleGenerator</classname>
                                        <substitutiontag>TITLE</substitutiontag>
                                </ClassGenerator>
                                <ClassGenerator>
                                        <classname>FooterGenerator</classname>
                                        <substitutiontag>FOOTER</substitutiontag>
                                </ClassGenerator>
                              
                        </generators>
        </layout>

</server>
